version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '03:00'
      timezone: 'Asia/Ho_Chi_Minh'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'chore(deps)'
    labels:
      - 'dependencies'
