name: Visual Regression

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Commitlint (PR only)
        if: ${{ github.event_name == 'pull_request' }}
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.sha }}

      - name: Install Dependencies
        run: npm ci

      - name: Check formatting
        run: npm run check:format

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Start Preview Server
        run: |
          npm run preview -- --host 0.0.0.0 --port 5173 &
          sleep 3

      - name: Snapshot live site
        run: npm run snapshot

      - name: Visual test (pages only)
        run: npm run test:visual:pages
        env:
          PAGES_ONLY: '1'

      - name: Upload visual report
        uses: actions/upload-artifact@v4
        with:
          name: visual-diff
          path: visual-diff
